apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: heart_pre
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.name }}
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: heart_pre
  type: NodePort
status:
  loadBalancer: {}
